name: "GDS Cluster Config Screamer"
description: "Provides validation for GDS Cluster Configs"
author: Shawn Rushefsky
inputs:
  token:
    description: Should be secrets.GITHUB_TOKEN
    required: true
  cluster_map:
    description: A URL where a JSON mapping of cluster attributes can be retrieved
    required: false
    default: https://static.glgresearch.com/gds-cluster-map/cluster-map.json
  aws_account_id:
    description: The ID of your AWS account. Used to generate certain comments.
    required: false
    default: "*"
  aws_secrets_prefix:
    description: A string to prefix your secrets with, i.e. us-east-1/production/
    required: false
    default: "us-east-1/production/"
  aws_region:
    description: Your AWS region. Used to generate certain comments
    required: false
    default: "us-east-1"
  aws_partition:
    description: Your AWS partition. Like 'aws', 'aws-cn', etc.
    required: false
    default: aws
  num_services_warn:
    description: The number of services that can be in the cluster before getting a warning
    required: false
    default: 50
  num_services_fail:
    description: The number of services that can be in the cluster before future services are rejected
    required: false
    default: 100
  cluster_root:
    description: The path of the root of the cluster
    required: false
    default: "."
  deployinator_token:
    description: An App Token that can access an instance of Deployinator
    required: false
    default: ""
runs:
  using: "node12"
  main: "index.js"
branding:
  color: purple
  icon: eye
